// Host-compiled unit test, no ESP-IDF/hardware dependency.
// Build/run: gcc -I.. test_gfx.c ../gfx.c -o test_gfx && ./test_gfx
//
// Shape-primitive expected coordinate sets below were generated by running the actual
// shared/gfx.py GFX class (not hand-derived) with a pixel-callback recorder, for the exact
// same inputs used here -- see docs/REFACTOR-PLAN.md Phase 7 step 17. Regenerate with:
//
//   python3 -c "
//   import sys, types, builtins
//   builtins.ptr8 = builtins.ptr16 = builtins.ptr32 = object
//   builtins.micropython = types.SimpleNamespace(viper=lambda f: f, native=lambda f: f)
//   sys.path.insert(0, 'shared')
//   import gfx
//   pts = []
//   g = gfx.GFX(32, 32, lambda x, y, *a, **k: pts.append((int(x), int(y))))
//   g.<method>(<args>)
//   print(sorted(set(pts)))
//   "
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../display/gfx.h"

#define W 32
#define H 32
#define FB_BYTES (W * H / 8)

typedef struct {
    int x, y;
} pt_t;

static int pt_cmp(const void *a, const void *b)
{
    const pt_t *pa = a;
    const pt_t *pb = b;
    if (pa->x != pb->x) {
        return pa->x - pb->x;
    }
    return pa->y - pb->y;
}

static int collect_set_pixels(const uint8_t *fb, pt_t *out, int max_out)
{
    int n = 0;
    for (int y = 0; y < H; y++) {
        for (int x = 0; x < W; x++) {
            int idx = (y * W + x) >> 3;
            int shift = x & 7;
            if (fb[idx] & (1 << shift)) {
                assert(n < max_out);
                out[n].x = x;
                out[n].y = y;
                n++;
            }
        }
    }
    qsort(out, (size_t)n, sizeof(pt_t), pt_cmp);
    return n;
}

static void check_shape(const char *name, void (*draw)(uint8_t *fb), const pt_t *expected,
                        int n_expected)
{
    uint8_t fb[FB_BYTES];
    memset(fb, 0, sizeof(fb));
    draw(fb);

    pt_t actual[4096];
    int n_actual = collect_set_pixels(fb, actual, 4096);

    if (n_actual != n_expected) {
        fprintf(stderr, "%s: pixel count mismatch: got %d, expected %d\n", name, n_actual,
                n_expected);
        assert(0);
    }
    for (int i = 0; i < n_expected; i++) {
        if (actual[i].x != expected[i].x || actual[i].y != expected[i].y) {
            fprintf(stderr, "%s: mismatch at index %d: got (%d,%d), expected (%d,%d)\n", name, i,
                    actual[i].x, actual[i].y, expected[i].x, expected[i].y);
            assert(0);
        }
    }
}

// clang-format off
static void draw_rect(uint8_t *fb)             { gfx_rect(fb, W, H, 0, 0, 3, 3, 8, 6, 1); }
static void draw_circle(uint8_t *fb)           { gfx_circle(fb, W, H, 0, 0, 15, 15, 5, 1); }
static void draw_fill_circle(uint8_t *fb)      { gfx_fill_circle(fb, W, H, 0, 0, 15, 15, 4, 1); }
static void draw_line(uint8_t *fb)             { gfx_line(fb, W, H, 0, 0, 2, 2, 12, 6, 1); }
static void draw_line_steep(uint8_t *fb)       { gfx_line(fb, W, H, 0, 0, 2, 2, 6, 14, 1); }
static void draw_triangle(uint8_t *fb)         { gfx_triangle(fb, W, H, 0, 0, 2, 2, 14, 4, 6, 12, 1); }
static void draw_fill_triangle(uint8_t *fb)    { gfx_fill_triangle(fb, W, H, 0, 0, 2, 10, 14, 2, 8, 15, 1); }
static void draw_fill_triangle_neg(uint8_t *fb){ gfx_fill_triangle(fb, W, H, 0, 0, 12, 2, 2, 9, 15, 12, 1); }
static void draw_fill_triangle_flat(uint8_t *fb){ gfx_fill_triangle(fb, W, H, 0, 0, 2, 5, 10, 5, 6, 12, 1); }
static void draw_round_rect(uint8_t *fb)       { gfx_round_rect(fb, W, H, 0, 0, 2, 2, 14, 10, 3, 1); }
static void draw_fill_round_rect(uint8_t *fb)  { gfx_fill_round_rect(fb, W, H, 0, 0, 2, 2, 14, 10, 3, 1); }
// clang-format on

static void test_shapes_vs_python_reference(void)
{
    // clang-format off
    static const pt_t rect_pts[] = {
        {3,3},{3,4},{3,5},{3,6},{3,7},{3,8},{4,3},{4,8},{5,3},{5,8},{6,3},{6,8},
        {7,3},{7,8},{8,3},{8,8},{9,3},{9,8},{10,3},{10,4},{10,5},{10,6},{10,7},{10,8},
    };
    static const pt_t circle_pts[] = {
        {10,13},{10,14},{10,15},{10,16},{10,17},{11,12},{11,18},{12,11},{12,19},{13,10},
        {13,20},{14,10},{14,20},{15,10},{15,20},{16,10},{16,20},{17,10},{17,20},{18,11},
        {18,19},{19,12},{19,18},{20,13},{20,14},{20,15},{20,16},{20,17},
    };
    static const pt_t fill_circle_pts[] = {
        {11,14},{11,15},{11,16},{12,12},{12,13},{12,14},{12,15},{12,16},{12,17},{12,18},
        {13,12},{13,13},{13,14},{13,15},{13,16},{13,17},{13,18},{14,11},{14,12},{14,13},
        {14,14},{14,15},{14,16},{14,17},{14,18},{14,19},{15,11},{15,12},{15,13},{15,14},
        {15,15},{15,16},{15,17},{15,18},{15,19},{16,11},{16,12},{16,13},{16,14},{16,15},
        {16,16},{16,17},{16,18},{16,19},{17,12},{17,13},{17,14},{17,15},{17,16},{17,17},
        {17,18},{18,12},{18,13},{18,14},{18,15},{18,16},{18,17},{18,18},{19,14},{19,15},
        {19,16},
    };
    static const pt_t line_pts[] = {
        {2,2},{3,2},{4,3},{5,3},{6,4},{7,4},{8,4},{9,5},{10,5},{11,6},{12,6},
    };
    static const pt_t line_steep_pts[] = {
        {2,2},{2,3},{3,4},{3,5},{3,6},{4,7},{4,8},{4,9},{5,10},{5,11},{5,12},{6,13},{6,14},
    };
    static const pt_t triangle_pts[] = {
        {2,2},{2,3},{3,2},{3,4},{3,5},{4,2},{4,6},{4,7},{4,8},{5,2},{5,9},{5,10},{6,3},
        {6,11},{6,12},{7,3},{7,11},{8,3},{8,10},{9,3},{9,9},{10,3},{10,8},{11,3},{11,7},
        {12,4},{12,6},{13,4},{13,5},{14,4},
    };
    static const pt_t fill_triangle_pts[] = {
        {2,10},{3,9},{3,10},{3,11},{4,9},{4,10},{4,11},{4,12},{5,8},{5,9},{5,10},{5,11},
        {5,12},{5,13},{6,7},{6,8},{6,9},{6,10},{6,11},{6,12},{6,13},{6,14},{7,7},{7,8},
        {7,9},{7,10},{7,11},{7,12},{7,13},{7,14},{8,6},{8,7},{8,8},{8,9},{8,10},{8,11},
        {8,12},{8,13},{8,14},{8,15},{9,5},{9,6},{9,7},{9,8},{9,9},{9,10},{9,11},{9,12},
        {10,5},{10,6},{10,7},{10,8},{10,9},{10,10},{11,4},{11,5},{11,6},{11,7},{11,8},
        {12,3},{12,4},{12,5},{12,6},{13,3},{13,4},{14,2},
    };
    static const pt_t fill_triangle_neg_pts[] = {
        {2,9},{3,8},{3,9},{4,7},{4,8},{4,9},{5,7},{5,8},{5,9},{6,6},{6,7},{6,8},{6,9},
        {6,10},{7,5},{7,6},{7,7},{7,8},{7,9},{7,10},{8,5},{8,6},{8,7},{8,8},{8,9},{8,10},
        {9,4},{9,5},{9,6},{9,7},{9,8},{9,9},{9,10},{10,3},{10,4},{10,5},{10,6},{10,7},
        {10,8},{10,9},{10,10},{10,11},{11,3},{11,4},{11,5},{11,6},{11,7},{11,8},{11,9},
        {11,10},{11,11},{12,2},{12,3},{12,4},{12,5},{12,6},{12,7},{12,8},{12,9},{12,10},
        {12,11},{13,6},{13,7},{13,8},{13,9},{13,10},{13,11},{14,9},{14,10},{14,11},{15,12},
    };
    static const pt_t fill_triangle_flat_pts[] = {
        {2,5},{2,6},{3,5},{3,6},{3,7},{3,8},{4,5},{4,6},{4,7},{4,8},{4,9},{4,10},{5,5},
        {5,6},{5,7},{5,8},{5,9},{5,10},{5,11},{6,5},{6,6},{6,7},{6,8},{6,9},{6,10},{6,11},
        {6,12},{7,5},{7,6},{7,7},{7,8},{7,9},{7,10},{8,5},{8,6},{8,7},{8,8},{9,5},{9,6},
        {10,5},
    };
    static const pt_t round_rect_pts[] = {
        {2,4},{2,5},{2,6},{2,7},{2,8},{2,9},{2,10},{3,3},{3,11},{4,2},{4,12},{5,2},{5,13},
        {6,2},{6,13},{7,2},{7,13},{8,2},{8,13},{9,2},{9,13},{10,2},{10,13},{11,2},{11,13},
        {12,2},{12,13},{13,2},{13,13},{14,2},{14,12},{15,3},{15,11},{16,4},{16,5},{16,6},
        {16,7},{16,8},{16,9},{16,10},
    };
    static const pt_t fill_round_rect_pts[] = {
        {2,4},{2,5},{2,6},{2,7},{2,8},{2,9},{2,10},{3,3},{3,4},{3,5},{3,6},{3,7},{3,8},
        {3,9},{3,10},{3,11},{4,2},{4,3},{4,4},{4,5},{4,6},{4,7},{4,8},{4,9},{4,10},{4,11},
        {4,12},{5,2},{5,3},{5,4},{5,5},{5,6},{5,7},{5,8},{5,9},{5,10},{5,11},{5,12},{5,13},
        {6,2},{6,3},{6,4},{6,5},{6,6},{6,7},{6,8},{6,9},{6,10},{6,11},{6,12},{6,13},{7,2},
        {7,3},{7,4},{7,5},{7,6},{7,7},{7,8},{7,9},{7,10},{7,11},{7,12},{7,13},{8,2},{8,3},
        {8,4},{8,5},{8,6},{8,7},{8,8},{8,9},{8,10},{8,11},{8,12},{8,13},{9,2},{9,3},{9,4},
        {9,5},{9,6},{9,7},{9,8},{9,9},{9,10},{9,11},{9,12},{9,13},{10,2},{10,3},{10,4},
        {10,5},{10,6},{10,7},{10,8},{10,9},{10,10},{10,11},{10,12},{10,13},{11,2},{11,3},
        {11,4},{11,5},{11,6},{11,7},{11,8},{11,9},{11,10},{11,11},{11,12},{11,13},{12,2},
        {12,3},{12,4},{12,5},{12,6},{12,7},{12,8},{12,9},{12,10},{12,11},{12,12},{12,13},
        {13,2},{13,3},{13,4},{13,5},{13,6},{13,7},{13,8},{13,9},{13,10},{13,11},{13,12},
        {13,13},{14,2},{14,3},{14,4},{14,5},{14,6},{14,7},{14,8},{14,9},{14,10},{14,11},
        {14,12},{14,13},{15,3},{15,4},{15,5},{15,6},{15,7},{15,8},{15,9},{15,10},{15,11},
        {16,4},{16,5},{16,6},{16,7},{16,8},{16,9},{16,10},
    };
    // clang-format on

    check_shape("rect", draw_rect, rect_pts, (int)(sizeof(rect_pts) / sizeof(rect_pts[0])));
    check_shape("circle", draw_circle, circle_pts,
                (int)(sizeof(circle_pts) / sizeof(circle_pts[0])));
    check_shape("fill_circle", draw_fill_circle, fill_circle_pts,
                (int)(sizeof(fill_circle_pts) / sizeof(fill_circle_pts[0])));
    check_shape("line", draw_line, line_pts, (int)(sizeof(line_pts) / sizeof(line_pts[0])));
    check_shape("line_steep", draw_line_steep, line_steep_pts,
                (int)(sizeof(line_steep_pts) / sizeof(line_steep_pts[0])));
    check_shape("triangle", draw_triangle, triangle_pts,
                (int)(sizeof(triangle_pts) / sizeof(triangle_pts[0])));
    check_shape("fill_triangle", draw_fill_triangle, fill_triangle_pts,
                (int)(sizeof(fill_triangle_pts) / sizeof(fill_triangle_pts[0])));
    // Exercises floordiv(): vertices aren't x-sorted, so dx01/dx02/dx12 go negative.
    check_shape("fill_triangle_neg", draw_fill_triangle_neg, fill_triangle_neg_pts,
                (int)(sizeof(fill_triangle_neg_pts) / sizeof(fill_triangle_neg_pts[0])));
    // y0 == y1 (flat top edge): exercises the `last = y1 - 1` branch.
    check_shape("fill_triangle_flat_top", draw_fill_triangle_flat, fill_triangle_flat_pts,
                (int)(sizeof(fill_triangle_flat_pts) / sizeof(fill_triangle_flat_pts[0])));
    check_shape("round_rect", draw_round_rect, round_rect_pts,
                (int)(sizeof(round_rect_pts) / sizeof(round_rect_pts[0])));
    check_shape("fill_round_rect", draw_fill_round_rect, fill_round_rect_pts,
                (int)(sizeof(fill_round_rect_pts) / sizeof(fill_round_rect_pts[0])));
}

static int mono_bit(const uint8_t *fb, int w, int x, int y)
{
    int idx = (y * w + x) >> 3;
    int shift = x & 7;
    return (fb[idx] >> shift) & 1;
}

static int gs4_nibble(const uint8_t *fb, int w, int x, int y)
{
    int byte_index = y * (w / 2) + (x >> 1);
    int shift = (x & 1) * 4;
    return (fb[byte_index] >> shift) & 0x0F;
}

// gfx_set_pixel's rotation remap, hand-computed against write_pixel_viper's original
// formula (boards/inkplate10/inkplate10.py) for a small 8x4 canvas.
static void test_set_pixel_rotation(void)
{
    uint8_t fb[4];

    // rotation 0: (3,1) -> px=3,py=1 -> idx=1, bit3.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 4, 0, 0, 3, 1, 1);
    assert(fb[1] == 0x08);

    // rotation 1 (90 CW): logical (1,5) -> px=y=5, py=h-1-x=4-1-1=2 -> idx=2, bit5.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 4, 1, 0, 1, 5, 1);
    assert(fb[2] == 0x20);

    // rotation 2 (180): logical (0,0) -> px=w-1-x=7, py=h-1-y=3 -> idx=3, bit7.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 4, 2, 0, 0, 0, 1);
    assert(fb[3] == 0x80);

    // rotation 3 (270 CCW): logical (0,0) -> px=w-1-y=7, py=x=0 -> idx=0, bit7.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 4, 3, 0, 0, 0, 1);
    assert(fb[0] == 0x80);

    // Out-of-bounds is a silent no-op, not a crash/corruption.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 4, 0, 0, 8, 0, 1);
    gfx_set_pixel(fb, 8, 4, 0, 0, -1, 0, 1);
    for (size_t i = 0; i < sizeof(fb); i++) {
        assert(fb[i] == 0);
    }
}

// GS4_HMSB packing: even x -> low nibble, odd x -> high nibble (docs/REFACTOR-PLAN.md
// Phase 5 step 15's fix), raw level 0-7 (not the old 2bpp 0-3 clamp).
static void test_set_pixel_gs4_packing(void)
{
    uint8_t fb[8];
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 2, 0, 1, 0, 0, 5); // even x -> low nibble
    gfx_set_pixel(fb, 8, 2, 0, 1, 1, 0, 6); // odd x -> high nibble
    assert(fb[0] == 0x65);
    assert(gs4_nibble(fb, 8, 0, 0) == 5);
    assert(gs4_nibble(fb, 8, 1, 0) == 6);

    // Raw value is masked to 3 bits, not clamped to the old 0-3 range.
    memset(fb, 0, sizeof(fb));
    gfx_set_pixel(fb, 8, 2, 0, 1, 2, 0, 15);
    assert(gs4_nibble(fb, 8, 2, 0) == 7);
}

// Hand-built 4x3 glyph (row_bytes = ceil(4/8) = 1 byte/row, MSB-first per row, matching
// shared/gfx_standard_font_01.py-style get_ch() output):
//   row0: 1010   row1: 0110   row2: 1111
static const uint8_t glyph_4x3[3] = {0xA0, 0x60, 0xF0};

// Replaces gfx.py's separate _draw_char_1bpp/_draw_char_2bpp test coverage -- this is the
// fix for the found bug where text drawn in GS mode still packed 2bpp/0-3 into a buffer
// that's been 4bpp/0-7 (GS4_HMSB) since Phase 5 step 14.
static void test_draw_char_mono(void)
{
    uint8_t fb[FB_BYTES];
    memset(fb, 0, sizeof(fb));
    gfx_draw_char(fb, W, H, 0, 0, 0, 0, glyph_4x3, 4, 3, 1, 1);

    static const pt_t expected[] = {
        {0, 0}, {0, 2}, {1, 1}, {1, 2}, {2, 0}, {2, 1}, {2, 2}, {3, 2},
    };
    pt_t actual[16];
    int n = collect_set_pixels(fb, actual, 16);
    assert(n == (int)(sizeof(expected) / sizeof(expected[0])));
    for (int i = 0; i < n; i++) {
        assert(actual[i].x == expected[i].x && actual[i].y == expected[i].y);
    }
}

static void test_draw_char_scaled(void)
{
    uint8_t fb[FB_BYTES];
    memset(fb, 0, sizeof(fb));
    gfx_draw_char(fb, W, H, 0, 0, 0, 0, glyph_4x3, 4, 3, 2, 1);

    // Glyph (0,0) is on -> the 2x2 block at (0,0)-(1,1) should all be set.
    assert(mono_bit(fb, W, 0, 0) == 1);
    assert(mono_bit(fb, W, 1, 0) == 1);
    assert(mono_bit(fb, W, 0, 1) == 1);
    assert(mono_bit(fb, W, 1, 1) == 1);
    // Glyph (1,0) is off -> its 2x2 block stays clear.
    assert(mono_bit(fb, W, 2, 0) == 0);
    assert(mono_bit(fb, W, 3, 0) == 0);
    assert(mono_bit(fb, W, 2, 1) == 0);
    assert(mono_bit(fb, W, 3, 1) == 0);
}

static void test_draw_char_gs4(void)
{
    uint8_t fb[12]; // phys_w=8 (4 bytes/row) x phys_h=3 -> 12 bytes
    memset(fb, 0, sizeof(fb));
    gfx_draw_char(fb, 8, 3, 0, 1, 0, 0, glyph_4x3, 4, 3, 1, 5);

    // Row 0 glyph bits: col0=1, col2=1 -> raw level 5 at x=0 and x=2, untouched elsewhere.
    assert(gs4_nibble(fb, 8, 0, 0) == 5);
    assert(gs4_nibble(fb, 8, 1, 0) == 0);
    assert(gs4_nibble(fb, 8, 2, 0) == 5);
    assert(gs4_nibble(fb, 8, 3, 0) == 0);
}

int main(void)
{
    test_shapes_vs_python_reference();
    test_set_pixel_rotation();
    test_set_pixel_gs4_packing();
    test_draw_char_mono();
    test_draw_char_scaled();
    test_draw_char_gs4();
    printf("test_gfx: all tests passed\n");
    return 0;
}
